spring:
  datasource:
    url: jdbc:mysql://117.72.48.233:3308/location_app?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: wky040110123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

server:
  port: 8000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
